[build]
  command = "pnpm install && pnpm run build"
  publish = ".output/public"
  edge_functions = "true"

[build.environment]
  NITRO_PRESET = "netlify"
  PNPM_FLAGS = "--shamefully-hoist"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 