[build]
  command = "pnpm run generate"
  publish = "dist"

[build.environment]
  PNPM_FLAGS = "--shamefully-hoist"
  NITRO_PRESET = "netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 