[build]
  command = "pnpm install && pnpm run build"
  publish = "dist"
  functions = ".output/server"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../package-lock.json"

[build.environment]
  NITRO_PRESET = "netlify"
  PNPM_FLAGS = "--shamefully-hoist"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 